# Generated by Django 4.2.13 on 2024-05-21 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="energyconsumption",
            name="actual_rate",
        ),
        migrations.RemoveField(
            model_name="energyconsumption",
            name="electric",
        ),
        migrations.RemoveField(
            model_name="energyconsumption",
            name="pressure",
        ),
        migrations.RemoveField(
            model_name="energyconsumption",
            name="standard_rate",
        ),
        migrations.RemoveField(
            model_name="energyconsumption",
            name="temperature",
        ),
        migrations.RemoveField(
            model_name="energyconsumption",
            name="volume",
        ),
        migrations.RemoveField(
            model_name="equipment",
            name="rating",
        ),
        migrations.AddField(
            model_name="energyconsumption",
            name="cost",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="equipment",
            name="actual_rate",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="equipment",
            name="electric",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="equipment",
            name="pressure",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="equipment",
            name="standard_rate",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="equipment",
            name="temperature",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="equipment",
            name="volume",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
