# Generated by Django 4.2.13 on 2024-05-22 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0002_remove_energyconsumption_actual_rate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="energyconsumption",
            name="energy_used",
            field=models.FloatField(default=0.0),
        ),
    ]
