# Generated by Django 4.2.13 on 2024-05-22 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0003_alter_energyconsumption_energy_used"),
    ]

    operations = [
        migrations.AddField(
            model_name="energyconsumption",
            name="expect_cost",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="energyconsumption",
            name="expect_used",
            field=models.FloatField(default=0.0),
        ),
    ]
