# Generated by Django 4.2.13 on 2024-05-22 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0004_energyconsumption_expect_cost_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipment",
            name="standard_rate",
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
