# Generated by Django 4.2.13 on 2024-05-22 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0005_alter_equipment_standard_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="energysource",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="equipment.energysource",
            ),
        ),
    ]
