# Generated by Django 4.2.13 on 2024-05-22 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0006_energysource_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="energysource",
            name="level",
            field=models.IntegerField(default=1),
        ),
    ]
