# Generated by Django 4.2.13 on 2024-05-22 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0007_energysource_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipment",
            name="standard_rate",
            field=models.FloatField(blank=True, default=0.00205),
        ),
    ]
