# Generated by Django 4.2.13 on 2024-05-22 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0008_alter_equipment_standard_rate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipment",
            name="standard_rate",
            field=models.FloatField(blank=True, default=2.05e-05),
        ),
    ]
